const { Activity } = require('../models');

// Note: 
// * risk level based on 1-5 (1 being low risk, 5 beign highest risk)
// * maximum participants set to 20 for all activities
// * minimum participants set to 1 for all activities

// Activity Seed Data
const activitydata = [
  {
    activity_name: 'Jogging',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Walking',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Running',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Rollerblading',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Football',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Soccer',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Tennis',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Weight Lifting',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'yes',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Basketball',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Volleyball',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: '',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Baseball',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: '',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Rugby',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Lacrosse',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Ultimate Frisbee',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name: 'Golfing',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Croquet',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Boating',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Sailing',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Canoeing',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Kayaking',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Rafting',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'permit',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Rowing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Dragonboating',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Seadooing',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 5,
    fee: 'yes',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Swimming',
    type: 'exercise',
    category: 'pleasure',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Beach',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Surfing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Scuba Diving',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Snorkeling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Bicycling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: '',
    risk_level: '',
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'ATV',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    activity_name:'Skiing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    activity_name:'Snowboarding',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    activity_name:'Snowmobiling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    activity_name:'Cross-Country Skiing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    activity_name:'Snowshoeing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // All season
  {
    activity_name:'Hunting',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
    // All season
  {
    activity_name:'Fishing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Camping',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Picnicking',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Barbecue',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Skating',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 3,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Ice Hockey',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Curling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Bird Watching',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Photography',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Exercise',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Tai Chi',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Yoga',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Park',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Playground',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Mountain Climbing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Geocaching',
    type: 'fun',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Badminton',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    activity_name:'Hiking',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  }
];

const seedActivity = () => Activity.bulkCreate(activitydata);

module.exports = seedActivity;