const { Activity } = require('../models');

const activitydata = [
  {
    title: 'Jogging',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/person-architecture-boardwalk-bridge-running-walkway-jogging-exercise-fitness-sports-physical-exercise-human-action-6211.jpg'
  },
  {
    title: 'Walking',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/beach-sea-coast-sand-walking-winter-group-vacation-shadow-holiday-friendship-tourism-friends-wadden-city-walk-schiermonnikoog-west-frisian-909000.jpg'
  },
  {
    title: 'Running',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/girls-summer-sport-fitness-training-lifestyle-healthy-park-nature-outdoor-workout-young-adult-exercise-fit-beautiful-active-female-women-activity-people-sporty-health-outside-athlete-person-morning-caucasian-athletic-wellness-leisure-green-portrait-sunny-grass-one-spring-smiling-enjoy-body-sportswear-beauty-lady-black-hair-brunette-People-in-nature-jogging-running-recreation-fun-physical-fitness-walking-shoulder-joint-photography-leggings-tights-textile-individual-sports-happy-street-fashion-yoga-pant-trousers-gesture-autumn-1629576.jpg'
  },
  {
    title: 'Rollerblading',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/bridge-stair-skate-walkway-recreation-jumping-green-park-leisure-rollerblade-inline-sports-playground-outdoor-recreation-playground-slide-72514.jpg'
  },
  {
    title: 'Football',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/man-grass-people-sport-field-game-play-male-green-action-soccer-professional-football-stadium-goal-player-activity-outdoors-competition-team-sports-ball-match-championship-event-tournament-league-success-score-win-football-player-competition-event-718541.jpg'
  },
  {
    title: 'Soccer',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/structure-sport-soccer-football-player-football-pitch-team-dress-sports-ball-shoot-rush-clip-duel-tackle-kicker-ball-sports-soccer-shoes-football-player-football-match-ball-game-sports-ground-playing-field-footballs-viewers-fire-doors-team-sport-fielder-opponents-footballers-shin-saver-football-boots-sport-venue-rugby-football-fussball-dress-1085512.jpg'
  },
  {
    title: 'Tennis',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/woman-sport-running-young-lifestyle-fitness-swing-competition-tennis-sports-net-ball-court-athlete-tournament-serve-return-racquet-racket-ball-game-tennis-player-racquet-sport-646068.jpg'
  },
  {
    title: 'Weight Lifting',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'yes',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/person-people-woman-female-young-youth-training-club-exercise-weight-lifestyle-health-fitness-trainer-gym-instructor-workout-caucasian-team-women-body-fit-lifting-shape-athlete-coach-active-strength-adult-powerful-personal-personal-training-personal-trainer-435643.jpg'
  },
  {
    title: 'Basketball',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sport-game-play-basketball-blue-basket-interior-design-arena-team-ball-917338.jpg'
  },
  {
    title: 'Volleyball',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: '',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/beach-sea-water-sand-ocean-group-people-sky-sport-game-play-jump-summer-recreation-young-athletic-playing-lifestyle-leisure-activity-fun-team-friends-sports-net-ball-active-volleyball-beach-volleyball-541644.jpg'
  },
  {
    title: 'Baseball',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: '',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sand-baseball-play-food-soil-stadium-baseball-field-gravel-sports-ball-flooring-sport-venue-557027.jpg'
  },
  {
    title: 'Rugby',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sport-field-game-play-run-equipment-football-goal-rugby-outdoors-sports-match-college-athletes-sprint-touchdown-tackle-teams-weight-training-rugby-player-rugby-football-rugby-union-rugby-league-rugby-sevens-1233636.jpg'
  },
  {
    title: 'Lacrosse',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: "https://get.pxhere.com/photo/sport-field-game-fall-player-team-sports-athlete-athletics-lax-ball-game-lacrosse-team-sport-stick-and-ball-games-box-lacrosse-stick-and-ball-sports-women's-lacrosse-953651.jpg"
  },
  {
    title: 'Ultimate Frisbee',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/lawn-play-recreation-frisbee-sports-playground-disc-golf-frisbee-golf-outdoor-recreation-557024.jpg'
  },
  {
    title: 'Golfing',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/structure-lawn-male-recreation-leisure-player-golf-golf-course-golfing-golf-club-sports-course-golfer-ball-game-outdoor-recreation-sport-venue-individual-sports-pitch-and-putt-1201237.jpg'
  },
  {
    title: 'Croquet',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/wood-vintage-antique-game-brown-wooden-ball-croquet-man-made-object-ancient-history-541900.jpg'
  },
  {
    title: 'Boating',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sea-sunset-boat-dusk-evening-vehicle-italy-venice-boating-venezia-gondola-gondolas-watercraft-canale-grande-watercraft-rowing-1012131.jpg'
  },
  {
    title: 'Sailing',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sea-coast-ocean-sky-sport-boat-adventure-wind-boot-vehicle-mast-sailing-banner-training-holiday-bay-blue-leisure-sailboat-sailing-school-competition-clouds-fun-holidays-sail-watercraft-schooner-athletes-sailing-boat-regatta-sailing-ship-lake-constance-summer-holiday-flyers-546228.jpg'
  },
  {
    title: 'Canoeing',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sea-water-girl-boat-sunlight-lake-adventure-canoe-paddle-reflection-vehicle-leisure-kayak-boating-paddling-watercraft-canoeing-watercraft-rowing-1293975.jpg'
  },
  {
    title: 'Kayaking',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sport-boat-paddle-vehicle-kayak-sports-equipment-boating-kayaking-watercraft-canoeing-sea-kayak-watercraft-rowing-888000.jpg'
  },
  {
    title: 'Rafting',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'permit',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/outdoor-sport-recreation-paddle-action-rapid-craft-extreme-extreme-sport-fitness-team-sports-boating-whitewater-teamwork-fast-challenge-raft-water-sport-rafting-outdoor-recreation-902013.jpg'
  },
  {
    title: 'Rowing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/water-nature-sport-boat-river-canal-summer-recreation-france-boot-bush-flow-paddle-mediterranean-vehicle-two-fish-rowing-boat-bank-women-sports-boating-helm-embankment-channel-quiet-rowing-canoeing-water-sports-channels-water-sport-outdoor-recreation-watercraft-rowing-canoe-sprint-863406.jpg'
  },
  {
    title: 'Dragonboating',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sport-boat-canoe-boot-paddle-vehicle-race-competition-sports-boating-watercraft-rowing-dragonboat-canoeing-water-sports-water-sport-dragon-boat-watercraft-rowing-canoe-sprint-974080.jpg'
  },
  {
    title: 'Seadooing',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 5,
    fee: 'yes',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sea-water-outdoor-boat-recreation-vehicle-reservoir-page-motorboat-activity-fun-sports-boating-watercraft-motorsport-water-sport-lake-powell-jet-ski-outdoor-recreation-wind-wave-powerboating-personal-water-craft-f1-powerboat-racing-seadoo-1357777.jpg'
  },
  {
    title: 'Swimming',
    type: 'exercise',
    category: 'pleasure',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sea-water-person-sunlight-wave-lake-paddle-reflection-swimming-swimmer-boating-physical-fitness-107952.jpg'
  },
  {
    title: 'Beach',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/beach-landscape-sea-coast-nature-sand-rock-ocean-horizon-cloud-sky-sun-sunrise-sunset-sunlight-morning-shore-wave-dawn-atmosphere-vacation-dusk-evening-reflection-holiday-seashore-california-material-body-of-water-hdr-waves-clouds-beautiful-afterglow-wind-wave-1033649.jpg'
  },
  {
    title: 'Surfing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sea-coast-ocean-shore-wave-surf-surfing-surfboard-extreme-sport-sports-water-sport-wind-wave-boardsport-surfing-equipment-and-supplies-surface-water-sports-bodyboarding-131439.jpg'
  },
  {
    title: 'Scuba Diving',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sea-water-recreation-diving-underwater-biology-float-extreme-sport-sports-breathing-apparatus-divers-underwater-world-water-sport-scuba-diving-air-bubbles-outdoor-recreation-scuba-divers-marine-biology-underwater-diving-divemaster-diving-suit-899332.jpg'
  },
  {
    title: 'Snorkeling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sea-water-ocean-people-recreation-diving-underwater-swimming-swimmer-dive-face-mask-diver-fun-snorkel-sports-snorkeling-water-sport-outdoor-recreation-marine-biology-1260466.jpg'
  },
  {
    title: 'Bicycling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: '',
    risk_level: 2,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/bicycle-bike-male-recreation-vehicle-healthy-sports-equipment-mountain-bike-cycling-bicyclist-sports-helmet-biking-racing-bicycling-active-biker-cardio-road-cycling-outdoor-recreation-cycle-sport-cyclo-cross-bicycle-bicycle-racing-road-bicycle-endurance-sports-racing-bicycle-hybrid-bicycle-road-bicycle-racing-duathlon-916809.jpg'
  },
  {
    title: 'ATV',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sand-vehicle-motorcycle-motocross-soil-cross-extreme-sport-race-sports-racing-quad-motorsport-atv-screenshot-all-terrain-vehicle-motorcycle-racing-off-roading-endurocross-dirt-track-racing-off-road-racing-640956.jpg'
  },
  // Winter
  {
    title: 'Skiing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/winter-snow-weather-winter-sport-sports-footwear-snowboard-skiing-snowboarding-alpine-skiing-downhill-extreme-sport-sports-equipment-vehicle-nordic-skiing-1367413.jpg'
  },
  // Winter
  {
    title: 'Snowboarding',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/silhouette-sky-sunset-snowboarder-snowboarding-48468.jpg'
  },
  // Winter
  {
    title: 'Snowmobiling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/landscape-mountain-snow-cold-winter-travel-recreation-transportation-vehicle-snowy-leisure-national-park-yellowstone-winter-sport-outdoors-tour-fun-sports-racing-riders-motorsport-vehicles-land-vehicle-auto-racing-snowmobiles-snowmobile-snow-machine-922675.jpg'
  },
  // Winter
  {
    title: 'Cross-Country Skiing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/landscape-snow-winter-trail-white-sport-recreation-equipment-skiing-leisure-season-sports-equipment-binding-trace-winter-sport-sunny-sports-downhill-ski-footwear-dynamic-piste-sticks-hilly-recovery-ski-touring-snow-lane-cross-country-skiing-cross-country-ski-nordic-skiing-ski-mountaineering-ski-equipment-outdoor-recreation-alpine-skiing-geological-phenomenon-telemark-skiing-long-l-uferin-langlaufschuh-1083833.jpg'
  },
  // Winter
  {
    title: 'Snowshoeing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/snow-winter-travel-recreation-equipment-usa-snowshoe-exercise-lifestyle-national-park-sports-equipment-winter-sport-outdoors-sports-trekking-resort-tourists-downhill-ski-footwear-active-piste-crater-lake-oregon-ranger-ski-touring-snowshoeing-nordic-skiing-ski-mountaineering-ski-equipment-geological-phenomenon-telemark-skiing-ski-cross-snowshoe-walk-815584.jpg'
  },
  // All season
  {
    title: 'Hunting',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/man-wilderness-walking-mountain-bird-hiking-field-adventure-dog-animal-mountain-range-male-recreation-gear-extreme-sport-pheasant-shooting-sports-backpacking-gun-hunt-catch-hunting-hunter-prey-shotgun-1259772.jpg'
  },
  // All season
  {
    title: 'Fishing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/hand-man-landscape-water-nature-outdoor-silhouette-person-sport-lake-river-male-recreation-standing-fishing-fisherman-natural-action-fish-lifestyle-leisure-activity-reel-rod-catch-active-casting-hobby-fishery-mature-recreational-outdoor-recreation-recreational-fishing-fly-rod-764532.jpg'
  },
  {
    title: 'Camping',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/sky-night-countryside-adventure-summer-dusk-evening-holiday-fire-camping-tourism-leisure-tent-outdoors-camper-camp-weekend-screenshot-campsite-camping-tent-atmosphere-of-earth-geological-phenomenon-638123.jpg'
  },
  {
    title: 'Picnicking',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/wood-basket-gingham-picnic-rainbow-137206.jpg'
  },
  {
    title: 'Barbecue',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/man-people-boy-dish-food-cooking-bbq-campfire-meat-barbecue-cuisine-grill-sausage-sausages-grilling-barbecue-grill-sense-outdoor-grill-animal-source-foods-722737.jpg'
  },
  {
    title: 'Skating',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 3,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/outdoor-snow-cold-winter-girl-skate-female-young-youth-weather-child-christmas-season-skating-snowman-santa-claus-ice-skating-ice-skates-669822.jpg'
  },
  {
    title: 'Ice Hockey',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/snow-winter-people-game-weather-playing-skiing-season-ice-hockey-winter-sport-ski-footwear-piste-freezing-ice-skating-nordic-skiing-ski-equipment-1390051.jpg'
  },
  {
    title: 'Curling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/snow-winter-sport-ice-stones-tubing-rink-curling-bonspiel-866647.jpg'
  },
  {
    title: 'Bird Watching',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/writing-watch-hiking-trail-driving-vacation-travel-europe-trip-map-font-spy-germany-bird-watching-binoculars-agent-spyglass-730053.jpg'
  },
  {
    title: 'Photography',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/hand-creative-camera-photography-photographer-backpack-driving-photo-dslr-lens-equipment-canon-studio-bag-gadget-professional-black-arm-modern-close-up-belt-focus-glasses-picture-digital-shoot-khaki-national-geographic-603128.jpg'
  },
  {
    title: 'Exercise',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/girl-model-spring-fashion-exercise-lady-photograph-stretch-stretching-beauty-photo-shoot-physical-fitness-21355.jpg'
  },
  {
    title: 'Tai Chi',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/italy-spiritual-meditation-sports-verona-martial-art-martial-tocat-tai-chi-taiji-qi-gong-qigong-inner-calm-piazza-herbs-chinese-martial-arts-491262.jpg'
  },
  {
    title: 'Yoga',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/hand-silhouette-person-light-shadow-human-darkness-black-yoga-adult-atmosphere-of-earth-physical-fitness-23886.jpg'
  },
  {
    title: 'Park',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/tree-nature-plant-leaf-flower-river-pond-stream-reflection-autumn-park-botany-garden-season-waterway-body-of-water-seasons-gardens-woodland-christchurch-parks-botanicalgardens-christchurchnz-publicgardens-hagleypark-woody-plant-342084.jpg'
  },
  {
    title: 'Playground',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/people-girl-bridge-play-boy-run-spring-color-child-smiling-playground-toddler-hand-in-hand-kids-running-outdoor-play-equipment-965974.jpg'
  },
  {
    title: 'Mountain Climbing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/rock-mountain-rope-adventure-mountain-range-recreation-alpine-climbing-extreme-sport-ridge-summit-climb-mountaineering-sports-alps-high-mountains-abseil-ski-touring-carbine-alpine-climbing-nordic-skiing-ski-mountaineering-climbing-rope-outdoor-recreation-prussik-knot-prusik-mountainous-landforms-mountain-guide-630450.jpg'
  },
  {
    title: 'Geocaching',
    type: 'fun',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/orienteering-running-gadget-geocaching-technology-electronic-device-tree-portable-communications-device-recreation-mobile-phone-communication-device-forest-finger-exercise-smartphone-plant-electronics-1517745.jpg'
  },
  {
    title: 'Badminton',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/grass-white-sport-lawn-meadow-play-green-speed-movement-leisure-feather-sports-equipment-golf-club-competition-sports-net-ball-bat-fast-badminton-strung-shuttle-coupon-racket-recreational-sports-ball-game-artificial-turf-lawn-game-tennis-racket-accessory-613709.jpg'
  },
  {
    title: 'Hiking',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1,
    image_url: 'https://get.pxhere.com/photo/man-landscape-water-waterfall-wilderness-walking-mountain-snow-people-sky-hiking-lake-boy-adventure-backpack-river-valley-mountain-range-high-blue-fjord-climbing-extreme-sport-tourism-ridge-mountaineering-stones-background-sports-alps-backpacking-plateau-fell-norway-beautifull-landform-holyday-mountainous-landforms-glacial-landform-bessegen-poupular-long-way-down-728990.jpg'
  }
];

const seedActivity = () => Activity.bulkCreate(activitydata);

module.exports = seedActivity;