const { Activity } = require('../models');

const activitydata = [
  {
    title: 'Jogging',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Walking',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Running',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Rollerblading',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Football',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Soccer',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Tennis',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Weight Lifting',
    type: 'exercise',
    category: 'fitness',
    style: 'physical',
    license_required: 'yes',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Basketball',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Volleyball',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: '',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Baseball',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: '',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Rugby',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Lacrosse',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Ultimate Frisbee',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title: 'Golfing',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Croquet',
    type: 'sport',
    category: 'fitness',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Boating',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Sailing',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Canoeing',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Kayaking',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Rafting',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'permit',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Rowing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Dragonboating',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Seadooing',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 5,
    fee: 'yes',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Swimming',
    type: 'exercise',
    category: 'pleasure',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Beach',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Surfing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Scuba Diving',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Snorkeling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Bicycling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: '',
    risk_level: 2,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'ATV',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    title:'Skiing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    title:'Snowboarding',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    title:'Snowmobiling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    title:'Cross-Country Skiing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // Winter
  {
    title:'Snowshoeing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  // All season
  {
    title:'Hunting',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
    // All season
  {
    title:'Fishing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Camping',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'yes',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Picnicking',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Barbecue',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Skating',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 3,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Ice Hockey',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 4,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Curling',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Bird Watching',
    type: 'sport',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'no',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Photography',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Exercise',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Tai Chi',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Yoga',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'yes',
    risk_level: 1,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Park',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Playground',
    type: 'fun',
    category: 'pleasure',
    style: 'leisure',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Mountain Climbing',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 5,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Geocaching',
    type: 'fun',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Badminton',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  },
  {
    title:'Hiking',
    type: 'sport',
    category: 'exercise',
    style: 'physical',
    license_required: 'no',
    risk_level: 2,
    fee: 'no',
    equipment: 'yes',
    max_participants: 20,
    min_participants: 1
  }
];

const seedActivity = () => Activity.bulkCreate(activitydata);

module.exports = seedActivity;